version: '3.7'

services:  
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
          
  dev_redis:
    image: redis
    container_name: mongorr_redis
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"  
    volumes:
      - redis_data_volume:/data

  dev_mongodb:
    image: mongo:latest
    container_name: "mongorr_mongodb"
    environment:
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_data_volume:/data/db
    ports:
      - 27017:27017

volumes:
  redis_data_volume:
  mongodb_data_volume: