version: '3.7'

services:  
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data_volume:/data
      
  dev_redis:
    image: redis
    container_name: redis-local
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"  
    volumes:
      - redis_data_volume:/data

volumes:
  redis_data_volume:
  dynamodb_data_volume:
